; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -Os -ffunction-sections -fdata-sections -Wl,--gc-sections -DTEST=0 -DDEBUG=0 -DCHANNEL=42

[env:uno-debug]
platform = atmelavr
board = uno
framework = arduino
build_flags = -Os -ffunction-sections -fdata-sections -Wl,--gc-sections -DTEST=1 -DDEBUG=1 -DCHANNEL=42

[env:native]
platform = native
build_flags =
    -pipe
    -I test/mocks
    -I src
    -D__AVR_ATmega328P__
    -DCHANNEL=42
    -DTEST=0
    -DDEBUG=0
test_framework = unity
